1 entries in records
1 entries in records
üîπ Extracting schema from SQL Server source: dwh.ga4_details
üîπ Extracting schema from SQL Server source: dwh.ga4_details
‚ùå Error processing record ga4_details: (psycopg2.errors.UndefinedColumn) column "precision" of relation "source_lookup" does not exist
LINE 1: ...column_id, column_name, source_data_type, length, precision,...
                                                             ^

[SQL: INSERT INTO ods.source_lookup (column_id, column_name, source_data_type, length, precision, scale, nullable, key_constraint, source_type, source_schema, source_table, target_table) VALUES (%(column_id__0)s, %(column_name__0)s, %(source_data_type__0)s ... 1252 characters truncated ... constraint__5)s, %(source_type__5)s, %(source_schema__5)s, %(source_table__5)s, %(target_table__5)s)]
[parameters: {'source_schema__0': 'dwh', 'scale__0': 0.0, 'precision__0': 10.0, 'source_type__0': 'SQL Server', 'source_table__0': 'ga4_details', 'target_table__0': 'stg_ga4_details', 'column_name__0': 'id', 'nullable__0': True, 'column_id__0': 1, 'key_constraint__0': 'PRIMARY KEY', 'length__0': None, 'source_data_type__0': 'int', 'source_schema__1': 'dwh', 'scale__1': 0.0, 'precision__1': 10.0, 'source_type__1': 'SQL Server', 'source_table__1': 'ga4_details', 'target_table__1': 'stg_ga4_details', 'column_name__1': 'propertyid', 'nullable__1': True, 'column_id__1': 2, 'key_constraint__1': '', 'length__1': None, 'source_data_type__1': 'int', 'source_schema__2': 'dwh', 'scale__2': None, 'precision__2': None, 'source_type__2': 'SQL Server', 'source_table__2': 'ga4_details', 'target_table__2': 'stg_ga4_details', 'column_name__2': 'metrics_date', 'nullable__2': True, 'column_id__2': 3, 'key_constraint__2': '', 'length__2': None, 'source_data_type__2': 'date', 'source_schema__3': 'dwh', 'scale__3': None, 'precision__3': None, 'source_type__3': 'SQL Server', 'source_table__3': 'ga4_details', 'target_table__3': 'stg_ga4_details', 'column_name__3': 'unifiedpagepathscreen', 'nullable__3': True, 'column_id__3': 4, 'key_constraint__3': '', 'length__3': -1.0, 'source_data_type__3': 'nvarchar', 'source_schema__4': 'dwh', 'scale__4': 0.0, 'precision__4': 10.0, 'source_type__4': 'SQL Server', 'source_table__4': 'ga4_details', 'target_table__4': 'stg_ga4_details', 'column_name__4': 'sessions', 'nullable__4': True, 'column_id__4': 5, 'key_constraint__4': '', 'length__4': None, 'source_data_type__4': 'int', 'source_schema__5': 'dwh', 'scale__5': None, 'precision__5': None, 'source_type__5': 'SQL Server', 'source_table__5': 'ga4_details', 'target_table__5': 'stg_ga4_details', 'column_name__5': 'etl_createddate', 'nullable__5': True, 'column_id__5': 6, 'key_constraint__5': '', 'length__5': None, 'source_data_type__5': 'datetime'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
‚ùå Error processing record ga4_details: (psycopg2.errors.UndefinedColumn) column "precision" of relation "source_lookup" does not exist
LINE 1: ...column_id, column_name, source_data_type, length, precision,...
                                                             ^

[SQL: INSERT INTO ods.source_lookup (column_id, column_name, source_data_type, length, precision, scale, nullable, key_constraint, source_type, source_schema, source_table, target_table) VALUES (%(column_id__0)s, %(column_name__0)s, %(source_data_type__0)s ... 1252 characters truncated ... constraint__5)s, %(source_type__5)s, %(source_schema__5)s, %(source_table__5)s, %(target_table__5)s)]
[parameters: {'source_schema__0': 'dwh', 'scale__0': 0.0, 'precision__0': 10.0, 'source_type__0': 'SQL Server', 'source_table__0': 'ga4_details', 'target_table__0': 'stg_ga4_details', 'column_name__0': 'id', 'nullable__0': True, 'column_id__0': 1, 'key_constraint__0': 'PRIMARY KEY', 'length__0': None, 'source_data_type__0': 'int', 'source_schema__1': 'dwh', 'scale__1': 0.0, 'precision__1': 10.0, 'source_type__1': 'SQL Server', 'source_table__1': 'ga4_details', 'target_table__1': 'stg_ga4_details', 'column_name__1': 'propertyid', 'nullable__1': True, 'column_id__1': 2, 'key_constraint__1': '', 'length__1': None, 'source_data_type__1': 'int', 'source_schema__2': 'dwh', 'scale__2': None, 'precision__2': None, 'source_type__2': 'SQL Server', 'source_table__2': 'ga4_details', 'target_table__2': 'stg_ga4_details', 'column_name__2': 'metrics_date', 'nullable__2': True, 'column_id__2': 3, 'key_constraint__2': '', 'length__2': None, 'source_data_type__2': 'date', 'source_schema__3': 'dwh', 'scale__3': None, 'precision__3': None, 'source_type__3': 'SQL Server', 'source_table__3': 'ga4_details', 'target_table__3': 'stg_ga4_details', 'column_name__3': 'unifiedpagepathscreen', 'nullable__3': True, 'column_id__3': 4, 'key_constraint__3': '', 'length__3': -1.0, 'source_data_type__3': 'nvarchar', 'source_schema__4': 'dwh', 'scale__4': 0.0, 'precision__4': 10.0, 'source_type__4': 'SQL Server', 'source_table__4': 'ga4_details', 'target_table__4': 'stg_ga4_details', 'column_name__4': 'sessions', 'nullable__4': True, 'column_id__4': 5, 'key_constraint__4': '', 'length__4': None, 'source_data_type__4': 'int', 'source_schema__5': 'dwh', 'scale__5': None, 'precision__5': None, 'source_type__5': 'SQL Server', 'source_table__5': 'ga4_details', 'target_table__5': 'stg_ga4_details', 'column_name__5': 'etl_createddate', 'nullable__5': True, 'column_id__5': 6, 'key_constraint__5': '', 'length__5': None, 'source_data_type__5': 'datetime'}]
(Background on this error at: https://sqlalche.me/e/20/f405)
Finished running source to staging in series
Finished running source to staging in series
Total time taken 1.01 seconds
Total time taken 1.01 seconds
